Add runtime params --long-dist-demand-forecast and --freight-matrix-path
Traficom/lem-model-system pull request #14
Opened 2024-06-05 10:26 UTC by zptro

2024-06-06 07:49 UTC, zptro commented on Scripts/modelsystem.py
> +                    self.mapping, long_dist_classes) as mtx:
This is the only functional change here, but unfortunately the change of indentation hides it.

2024-06-06 09:03 UTC, attesn requested changes
Test run gave error below when using command line and dev-config.json settings.

Other minor issue for discussion is misspelled paths. Using erroneous path led to error message `OSError: ``demand_vrk.omx`` does not exist`. Should correct paths be validated?

2024-06-06 12:20 UTC, zptro commented on Scripts/lem.py
> +        else Path(args.long_dist_demand_forecast))
Thanks for pointing this out. I was about to update dev-config.json, but then I somehow forgot. Now it is fixed.

2024-06-06 12:25 UTC, zptro commented
> Test run gave error below when using command line and dev-config.json settings.
> 
> Other minor issue for discussion is misspelled paths. Using erroneous path led to error message `` OSError: ``demand_vrk.omx`` does not exist ``. Should correct paths be validated?

Validating paths is a tricky thing here, because that is normally done in `lem_validate_inputfiles.py` before all the model runs, but in this case the long-distance matrices (or even the directory where to find them) may not exist yet (because the long-distance demand calculation is one of the model runs that are supposed to be run).

2024-06-10 07:50 UTC, attesn approved these changes

2024-06-14 12:13 UTC, merged