Split purpose and mode names in `print_matrices`
Traficom/lem-model-system pull request #40
Opened 2024-08-13 15:12 UTC by attesn

Closes #38

2024-08-13 15:16 UTC, attesn commented
Didn't include it here, but I'd remove the Excel files for simplicity.

2024-08-14 07:53 UTC, zptro requested changes

2024-08-14 07:53 UTC, zptro commented on Scripts/datahandling/resultdata.py
> +            names=["mode", "orig", "dest"])
I played a bit with `pandas.concat` and realized that you can achieve the same result like this:

```suggestion
            {(description, key): df.stack() for key, df in data.items()},
            names=["purpose", "mode", "orig", "dest"])
```

2024-08-14 07:53 UTC, zptro commented on Scripts/datahandling/resultdata.py
> +        self.print_concat(stacked_matrices.set_index("purpose"), filename + ".txt")
These additions are then unnecessary

```suggestion
        self.print_concat(stacked_matrices, filename + ".txt")
```

2024-08-14 08:03 UTC, zptro approved these changes

2024-08-14 08:04 UTC, merged