Merging updated test network data into main
Traficom/lem-model-system pull request #89
Opened 2024-10-25 12:51 UTC by Konnde

Created new test network that has been tested to run through with latest main changes. Updated emme_only and without emme test_assignment python modules to cover changes in test network and main.

2024-10-28 07:55 UTC, zptro requested changes
Thanks for this! For the tests to pass, we still need to update the matrices (tests/test_data/base_input_data and tests/test_data/results/test) and some small details in the tests themselves. Do you want to give it a try or should I do it?

2024-10-28 08:22 UTC, Konnde commented
I can take this in order to learn more about the system! After glancing the failing build, indeed it seems that I forgot to update the matrices to match network centroids. I'll make the necessary updates.

2024-10-30 10:13 UTC, zptro submitted a review, later dismissed
This seems to work really well, great job!

2024-10-30 13:30 UTC, zptro approved these changes

2024-10-30 13:32 UTC, merged